import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'Index',
    {
      type: 'category',
      label: 'Installation',
      items: [
        'Installation/docker',
        'Installation/kubernetes',
        'Installation/local',
        'Installation/azure',
        'Installation/aws',
        'Installation/gcp',
        'Installation/aliyun',
        'Installation/tencent',
        'Installation/iis-proxy',
      ],
    },
    'migrating-from-bagetter',
    'upgrading',
    'feeds',
    'web-ui',
    'authentication',
    'configuration',
    {
      type: 'category',
      label: 'Import packages',
      items: [{type: 'autogenerated', dirName: 'Import'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{type: 'autogenerated', dirName: 'Advanced'}],
    },
    {
      type: 'category',
      label: 'Compared to',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'vs'}],
    },
  ],
};

export default sidebars;
